version: '3.8'

networks:
  dev_onlinepharmacydb:
    driver: bridge
  devportfolio:
    external: true

volumes:
  dev_sharedfilestorage:
    external: true
  dev_onlinepharmacyvol:
  dev_onlinepharmacydbvol:
  


services:

  dev-Onlinepharmacy-db:
    image: mysql:8.3.0
    container_name: dev-Onlinepharmacy-db
    restart: unless-stopped
    tty: true
    # ports:
    # - "${MYSQL_HOST_PORT}:${MYSQL_DOCKER_CONTAINER_PORT}"
    environment:
      MYSQL_DATABASE: "${onlinePharmacyDB}"
      MYSQL_ROOT_PASSWORD: "${onlinePharmacyDB_Password}"
      MYSQL_USER: "${mysql_user}"
      MYSQL_PASSWORD: "${mysql_password}"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

    networks:
      - dev_onlinepharmacydb
    volumes:
      - dev_onlinepharmacydbvol:/var/lib/mysql

  dev-phpmyadmin:
    image: phpmyadmin:5.2.0
    ports:
      - '8383:80'
    environment:
      - PMA_HOSTS=dev-Onlinepharmacy-db #Add more mysql services here.
    networks:
      - dev_onlinepharmacydb
    depends_on:
      - dev-Onlinepharmacy-db

  dev-onlinepharmacy:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: dev-onlinepharmacy
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www/html/
      - dev_sharedfilestorage:/var/www/html/storage/app/public
      - dev_sharedfilestorage:/public/storage/
    ports:
      - "${ONLINEPHARMACYPORT}:${ONLINEPHARMACYDOCKERPORT}"
    depends_on:
      - dev-Onlinepharmacy-db

    environment:
      DB_CONNECTION: mysql
      DB_HOST: dev-Onlinepharmacy-db
      DB_PORT: ${MYSQL_DOCKER_CONTAINER_PORT}
      DB_DATABASE: "${onlinePharmacyDB}"
      DB_USERNAME: "${mysql_user}"
      DB_PASSWORD: "${mysql_password}"
    
    networks:
      - dev_onlinepharmacydb
      - devportfolio
