#installing composer dependencies
FROM composer:2.7.1 as vendor

WORKDIR /app

COPY composer.json composer.lock ./

RUN composer install \
    --ignore-platform-reqs \
    --no-interaction \
    --no-plugins \
    --no-scripts \
    --prefer-dist

#building frontend assets
FROM node:18 as frontend

WORKDIR /app

RUN mkdir -p public
COPY package.json webpack.mix.js yarn.lock  /app/
COPY resources/ /app/resources/
COPY tailwind.config.js /app/
RUN npm install
RUN npm run production

#final stage with php-fpm
FROM php:8.1.15-fpm

# Set environment variables to override PHP configuration
ENV PHP_INI_UPLOAD_MAX_FILESIZE 32M
ENV PHP_INI_POST_MAX_SIZE 32M

# Install system dependencies (includes node)
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    gnupg \
    unzip 

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd


# Copy the project files to the container
COPY . .
COPY --from=vendor /app/vendor/ ./vendor/
COPY --from=frontend /app/public/js/ ./public/js/
COPY --from=frontend /app/public/css/ ./public/css/


# Set the correct permissions
RUN chmod -R 777 storage
